import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/Header';
import { Toaster } from '@/components/ui/toaster';
import AppProvider from '@/app/context/app-provider';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['vietnamese'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookiesStore = cookies();
	const sessionToken = cookiesStore.get('sessionToken');

	return (
		<html
			lang='en'
			suppressHydrationWarning>
			<body className={inter.className}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange>
					<Header />
					<AppProvider initSessionToken={sessionToken?.value ?? ''}>
						{children}
					</AppProvider>
				</ThemeProvider>
				<Toaster />
			</body>
		</html>
	);
}
